/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BisuSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
}
declare global {
    interface HTMLBisuSideDrawerElement extends Components.BisuSideDrawer, HTMLStencilElement {
    }
    var HTMLBisuSideDrawerElement: {
        prototype: HTMLBisuSideDrawerElement;
        new (): HTMLBisuSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "bisu-side-drawer": HTMLBisuSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface BisuSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface IntrinsicElements {
        "bisu-side-drawer": BisuSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bisu-side-drawer": LocalJSX.BisuSideDrawer & JSXBase.HTMLAttributes<HTMLBisuSideDrawerElement>;
        }
    }
}
